name: GitHub Actions CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ secrets.ENV_DATABASE_URL }}
          POSTGRES_USER: ${{ secrets.ENV_DATABASE_USER }}
          POSTGRES_PASSWORD: ${{ secrets.ENV_DATABASE_PASSWORD }}
          ports:
            - 5432:5432
          options: >-
            --health-cmd "pg_isready -U ${{ secrets.ENV_DATABASE_USER }}" 
            --health-interval 10s 
            --health-timeout 5s 
            --health-retries 5
    steps:
      - name: Debug
      - uses: raven-actions/debug@v1
      - with:
          vars-context: ${{ toJson(vars) }}  # optional
          secrets-context: ${{ toJson(secrets) }}  # optional
          needs-context: ${{ toJson(needs) }}  # optional
          inputs-context: ${{ toJson(inputs) }}

      - name: Checkout Code
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-  

      - name: Build and Test
        run: mvn clean install
        env:
          ENV_DATABASE_URL: ${{ secrets.ENV_DATABASE_URL }}
          ENV_DATABASE_USER: ${{ secrets.ENV_DATABASE_USER }}
          ENV_DATABASE_PASSWORD: ${{ secrets.ENV_DATABASE_PASSWORD }}

      - name: Static Code Analysis
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=test-deploy_crud
            -Dsonar.organization=test-deploy
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.java.binaries=**/target/classes

      - name: Security Vulnerabilities Scan
        uses: anchore/scan-action@v2
        with:
          image-reference: target/*.war

