name: GitHub Actions CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ secrets.ENV_DATABASE_URL }}
          POSTGRES_USER: ${{ secrets.ENV_DATABASE_USER }}
          POSTGRES_PASSWORD: ${{ secrets.ENV_DATABASE_PASSWORD }}
          ports:
            - 5432:5432
          options: >-
            --health-cmd "pg_isready -U ${{ secrets.ENV_DATABASE_USER }}" 
            --health-interval 10s 
            --health-timeout 5s 
            --health-retries 5
    steps:

      - name: Checkout Code
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar


      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build, test and analyze
        run: mvn -B clean install org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=test-deploy_crud
        env:
          ENV_DATABASE_URL: ${{ secrets.ENV_DATABASE_URL }}
          ENV_DATABASE_USER: ${{ secrets.ENV_DATABASE_USER }}
          ENV_DATABASE_PASSWORD: ${{ secrets.ENV_DATABASE_PASSWORD }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Security Vulnerabilities Scan
        uses: anchore/scan-action@v2
        with:
          image-reference: target/*.war

